### ISSUE TITLE
Cannot install react-native-simple-maps

### ISSUE THREAD

**Issue by JoBerkner** [ahushh/react-native-simple-maps#2]
I am trying to install `react-native-simple-maps` using `npm install react-native-simple-maps` , but I am not able to do it as it throws an error. Here is the last part of the log I get:

```
20 silly saveTree +-- react@16.9.0
20 silly saveTree `-- topojson-client@3.1.0
21 verbose stack Error: spawn git ENOENT
21 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
21 verbose stack     at onErrorNT (internal/child_process.js:415:16)
21 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
22 verbose cwd C:\Users\user\Documents\Geolic\__Projects\conxinuum
23 verbose Windows_NT 10.0.18362
24 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "react-native-simple-maps"
25 verbose node v10.16.3
26 verbose npm  v6.9.0
27 error path git
28 error code ENOENT
29 error errno ENOENT
30 error syscall spawn git
31 error enoent Error while executing:
31 error enoent undefined ls-remote -h -t git://github.com/ahushh/react-native-svg-pan-zoom.git
31 error enoent
31 error enoent
31 error enoent spawn git ENOENT
32 error enoent This is related to npm not being able to find a file.
33 verbose exit [ 1, true ]
```

Any idea why this happens?

---
PLUS: I only found your library for implementing d3 maps into react native. Do you know any other library that is capable of doing this?

**Comment by ahushh** [comment]
I'm not sure if it helps but try to upgrade npm to 6.12 and node to 12 or 13 versions. It looks like npm couldn't fetch git://github.com/ahushh/react-native-svg-pan-zoom.git or it could be some OS related issue

>Do you know any other library that is capable of doing this?
No, that's why I had to make it by myself.

**Comment by ahushh** [comment]
@JoBerkner I renamed react-native-svg-pan-zoom to react-native-simple-svg-pan-zoom and published it to npm. Without direct links to github It shouldn't throw any error. Please let me know if it works for you.

**Comment by JoBerkner** [comment]
@ahushh Thanks! It is working now!

I will see how I can use your library for my needs. But thanks for providing it!
